version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - postgres_data:/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file:
      - .env.${NODE_ENV}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailhog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
      - .env.${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
