version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cultura
      PGDATA: /data/postgres
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_SERVER_NAME: "CloudBeaver"
      CB_ADMIN_NAME: "admin"
      CB_ADMIN_PASSWORD: "admin"
    ports:
      - "8978:8978"
    depends_on:
      - postgres

volumes:
  postgres_data:
