FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD sh -c 'until nc -z postgres 5432; do echo "Waiting for PostgreSQL..."; sleep 5; done; \
           npx prisma migrate dev --name init && npm run dev'
